const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: ` Fluffy breakfast delicacies made with tangy buttermilk for a delightful morning treat. `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'dinner',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `A hearty meal at diners, typically featuring double portions of classic comfort foods like burgers, sandwiches, or breakfast plates.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `A monstrous-sized milkshake overflowing with layers of creamy ice cream, decadent toppings, and towering whipped cream, sure to satisfy any sweet tooth.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `A hearty and wholesome dish featuring a flavorful blend of rustic ingredients, evoking the warmth and comfort of countryside cooking.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `A culinary creation typically involving eggs, prepared in a variety of styles with bold flavors and ingredients, often showcasing the versatility of this breakfast staple.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `A luscious dessert or milkshake made with Oreo cookies, offering a heavenly combination of rich chocolate, creamy filling, and indulgent sweetness for a dreamy treat.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `A savory delight featuring an abundance of crispy bacon, often served in generous portions or as a key ingredient in dishes ranging from breakfast classics to indulgent sandwiches or salads.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Iconic dishes or products that have become quintessential symbols of American culinary culture, embodying tradition, familiarity, and nostalgia.`,
  },
];
export default menu;